version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql:8.2
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: "Asia/Tokyo"
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d
  express:
    container_name: express
    build:
      context: .
      dockerfile: ./dockerfiles/express.Dockerfile
    depends_on:
      - mysql
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports: # ホスト側:コンテナ側
      - 5555:5555
      - 8000:${PORT}
volumes:
  mysql:
